[package]
name = "rokol"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"
description = "Wrapper of Sokol"
repository = "https://github.com/toyboot4e/rokol"
keywords = ["gamedev"]
license = "MIT"
categories = ["game-engines"]

[dependencies]
log = "0.4.11"
bitflags = "1.2.1"
rokol_ffi = { path = "rokol_ffi" }

[dev-dependencies]
env_logger = "0.8.1"
image = "0.23.11"
