[package]
name = "rokol"
version = "0.1.1"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"
exclude = ["examples", "book"]
description = "Wrapper of Sokol"
repository = "https://github.com/toyboot4e/rokol"
license = "MIT"
categories = ["game-development", "graphics"]
keywords = ["graphics", "gamedev"]

[features]
# https://doc.rust-lang.org/cargo/reference/features.html#the-features-section
glcore33 = ["rokol_ffi/glcore33"]
metal = ["rokol_ffi/metal"]
d3d11 = ["rokol_ffi/d3d11"]

[dependencies]
log = "0.4.11"
bitflags = "1.2.1"
rokol_ffi = { path = "rokol_ffi", version = "0.1.1" }

[dev-dependencies]
env_logger = "0.8.1"
image = "0.23.11"
glam = "0.11.0"
# imgui = "0.6.0"
