= Rokol devlog
:sokol: https://github.com/floooh/sokol[Sokol]
:sokol-rs: https://github.com/code-disaster/sokol-rs[sokol-rs]
:bindgen: https://github.com/rust-lang/rust-bindgen[bindgen]
:miniquad: https://github.com/not-fl3/miniquad[miniquad]
:macroquad: https://github.com/not-fl3/macroquad[macroquad]
:fna3d: https://github.com/FNA-XNA/FNA3D[FNA3D]
:rust-fna3d: https://github.com/toyboot4e/rust-fna3d[Rust-FNA3D]

== Background

I'm interested in C libraries. They can be used from almost any other programming language. That's cool!

And I made a wrapper of {fna3d}: {rust-fna3d}. It was a lot of work, unfortunatelly, but it worked perfectly. So I'm temped to make more use of C libraries.

== Notes

This time, I'm trying {sokol}. Different from {fna3d}, it is a set of header-only libraries. The only one file does all the jobs? That's awesome!

{sokol-rs} was a pioneer wrapper, and it worked out of the box, but it was a bit outdated. So I'm making another, naming it Rokol.

NOTE: I would not recommend Rokol for others. There are native Rust frameworks: {miniquad} and {macroquad}. They're supre nice.

=== Nov 15, 2020

I started working with Rokol. I was already familar with `build.rs`, so it's been easier than I expected.

==== Why did I make another repository when there were sokol-rs?

Rokol has different styles from {sokol-rs}:

* Rokol uses {bindgen} to create Rust FFI to Sokol.
* Rokol changes function names.

One would use Rokol as this:

[source,rust]
----
use rokol::app as rapp;

rapp::run( .. );
----

Instead of importing all the items in a module:

[source,rust]
----
use sokol::app::*;

sapp_run( .. );
----

=== Nov 17, 2020

Rokol compiles conditionally. User has three options to select their renderer:

. Let Rokol select default renderer
. Use feature flag of `force-glcore33`
. Set `ROKOL_RENDERER` environment variable to force using some renderer. One of `GlCore33`, `Metal` or `D3D11` is allowed

Rokol user would also want to compile conditionally depending on Rokol renderer. That's possible if they add `rokol_ffi` to their `Cargo.toml` and write some build script. See `rokol/build.rs` and `rokol/examples/conditional.rs` for more details.

c.f. https://doc.rust-lang.org/cargo/reference/build-scripts.html[Build Scripts - The Cargo Book]

